/**
 * ENUMS - Các constants cho Music App
 * Học từ mô hình e-commerce: centralized enums để dễ maintain
 */

// ===== USER & ADMIN =====
const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  LOCKED: 'LOCKED',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION'
};

const ADMIN_ROLE = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
  CONTENT_MANAGER: 'CONTENT_MANAGER',
  SUPPORT: 'SUPPORT'
};

const ADMIN_ROLE_LABELS = {
  SUPER_ADMIN: 'Siêu quản trị viên',
  ADMIN: 'Quản trị viên',
  MODERATOR: 'Kiểm duyệt viên',
  CONTENT_MANAGER: 'Quản lý nội dung',
  SUPPORT: 'Hỗ trợ'
};

// ===== NOTIFICATION =====
const NOTIFICATION_TYPE = {
  LIKE: 'LIKE',
  COMMENT: 'COMMENT',
  REPLY: 'REPLY',
  FOLLOW: 'FOLLOW',
  SHARE: 'SHARE',
  ROOM_INVITE: 'ROOM_INVITE',
  PLAYLIST_UPDATE: 'PLAYLIST_UPDATE',
  NEW_RELEASE: 'NEW_RELEASE',
  SYSTEM: 'SYSTEM'
};

const NOTIFICATION_TYPE_LABELS = {
  LIKE: 'Thích',
  COMMENT: 'Bình luận',
  REPLY: 'Trả lời',
  FOLLOW: 'Theo dõi',
  SHARE: 'Chia sẻ',
  ROOM_INVITE: 'Mời vào phòng',
  PLAYLIST_UPDATE: 'Cập nhật playlist',
  NEW_RELEASE: 'Phát hành mới',
  SYSTEM: 'Hệ thống'
};

// ===== REPORT =====
const REPORT_TYPE = {
  SONG: 'SONG',
  PLAYLIST: 'PLAYLIST',
  COMMENT: 'COMMENT',
  USER: 'USER',
  ROOM: 'ROOM'
};

const REPORT_REASON = {
  SPAM: 'SPAM',
  INAPPROPRIATE: 'INAPPROPRIATE',
  COPYRIGHT: 'COPYRIGHT',
  FAKE: 'FAKE',
  HARASSMENT: 'HARASSMENT',
  OTHER: 'OTHER'
};

const REPORT_STATUS = {
  PENDING: 'PENDING',
  REVIEWING: 'REVIEWING',
  RESOLVED: 'RESOLVED',
  REJECTED: 'REJECTED'
};

const REPORT_REASON_LABELS = {
  SPAM: 'Spam',
  INAPPROPRIATE: 'Nội dung không phù hợp',
  COPYRIGHT: 'Vi phạm bản quyền',
  FAKE: 'Giả mạo',
  HARASSMENT: 'Quấy rối',
  OTHER: 'Khác'
};

const REPORT_STATUS_LABELS = {
  PENDING: 'Chờ xử lý',
  REVIEWING: 'Đang xem xét',
  RESOLVED: 'Đã xử lý',
  REJECTED: 'Từ chối'
};

// ===== SYSTEM LOG =====
const LOG_LEVEL = {
  INFO: 'INFO',
  WARNING: 'WARNING',
  ERROR: 'ERROR',
  CRITICAL: 'CRITICAL'
};

const LOG_CATEGORY = {
  AUTH: 'AUTH',
  USER: 'USER',
  SONG: 'SONG',
  PLAYLIST: 'PLAYLIST',
  ARTIST: 'ARTIST',
  ROOM: 'ROOM',
  SOCIAL: 'SOCIAL',
  SYSTEM: 'SYSTEM',
  ADMIN: 'ADMIN'
};

const ACTOR_TYPE = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  SYSTEM: 'SYSTEM'
};

// ===== MUSIC =====
const SHARE_TYPE = {
  FACEBOOK: 'FACEBOOK',
  TWITTER: 'TWITTER',
  WHATSAPP: 'WHATSAPP',
  LINK: 'LINK',
  OTHER: 'OTHER'
};

const PLAY_CONTEXT = {
  HOME: 'HOME',
  ROOM: 'ROOM',
  PLAYLIST: 'PLAYLIST',
  ALBUM: 'ALBUM',
  ARTIST: 'ARTIST',
  SEARCH: 'SEARCH',
  RECOMMENDATION: 'RECOMMENDATION',
  OTHER: 'OTHER'
};

const TIME_OF_DAY = {
  MORNING: 'MORNING',
  AFTERNOON: 'AFTERNOON',
  EVENING: 'EVENING',
  NIGHT: 'NIGHT'
};

const DAY_OF_WEEK = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY'
};

// ===== AI RECOMMENDATION =====
const RECOMMENDATION_ALGORITHM = {
  COLLABORATIVE: 'COLLABORATIVE',
  CONTENT: 'CONTENT',
  HYBRID: 'HYBRID',
  POPULAR: 'POPULAR',
  TRENDING: 'TRENDING'
};

// ===== RESPONSE CODES =====
const ResponseCode = {
  SUCCESS: 'SUCCESS',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  
  // User
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_LOCKED: 'USER_LOCKED',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  
  // Admin
  ADMIN_CREATED: 'ADMIN_CREATED',
  ADMIN_UPDATED: 'ADMIN_UPDATED',
  ADMIN_DELETED: 'ADMIN_DELETED',
  ADMIN_NOT_FOUND: 'ADMIN_NOT_FOUND',
  
  // Song
  SONG_CREATED: 'SONG_CREATED',
  SONG_UPDATED: 'SONG_UPDATED',
  SONG_DELETED: 'SONG_DELETED',
  SONG_NOT_FOUND: 'SONG_NOT_FOUND',
  
  // Playlist
  PLAYLIST_CREATED: 'PLAYLIST_CREATED',
  PLAYLIST_UPDATED: 'PLAYLIST_UPDATED',
  PLAYLIST_DELETED: 'PLAYLIST_DELETED',
  PLAYLIST_NOT_FOUND: 'PLAYLIST_NOT_FOUND',
  
  // Room
  ROOM_CREATED: 'ROOM_CREATED',
  ROOM_UPDATED: 'ROOM_UPDATED',
  ROOM_DELETED: 'ROOM_DELETED',
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  ROOM_FULL: 'ROOM_FULL',
  
  // Report
  REPORT_CREATED: 'REPORT_CREATED',
  REPORT_UPDATED: 'REPORT_UPDATED',
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  
  // Notification
  NOTIFICATION_CREATED: 'NOTIFICATION_CREATED',
  NOTIFICATION_UPDATED: 'NOTIFICATION_UPDATED',
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND'
};

// ===== GENDER =====
const GENDER = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER'
};

const GENDER_LABELS = {
  MALE: 'Nam',
  FEMALE: 'Nữ',
  OTHER: 'Khác'
};

// ===== LANGUAGE =====
const LANGUAGE = {
  VI: 'VI',
  EN: 'EN'
};

// ===== THEME =====
const THEME = {
  LIGHT: 'LIGHT',
  DARK: 'DARK',
  AUTO: 'AUTO'
};

// ===== ROOM ACTIVITY =====
const ROOM_ACTIVITY_TYPE = {
  USER_JOINED: 'USER_JOINED',
  USER_LEFT: 'USER_LEFT',
  USER_KICKED: 'USER_KICKED',
  SONG_ADDED: 'SONG_ADDED',
  SONG_REMOVED: 'SONG_REMOVED',
  SONG_SKIPPED: 'SONG_SKIPPED',
  SONG_STARTED: 'SONG_STARTED',
  SONG_ENDED: 'SONG_ENDED',
  PLAYBACK_PAUSED: 'PLAYBACK_PAUSED',
  PLAYBACK_RESUMED: 'PLAYBACK_RESUMED',
  ROOM_CREATED: 'ROOM_CREATED',
  ROOM_CLOSED: 'ROOM_CLOSED',
  SETTINGS_CHANGED: 'SETTINGS_CHANGED'
};

const ROOM_MESSAGE_TYPE = {
  TEXT: 'TEXT',
  EMOJI: 'EMOJI',
  STICKER: 'STICKER',
  SONG_SUGGESTION: 'SONG_SUGGESTION',
  SYSTEM: 'SYSTEM'
};

const ROOM_INVITATION_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED'
};

// ===== BANNER =====
const BANNER_TYPE = {
  PROMOTION: 'PROMOTION',
  NEW_RELEASE: 'NEW_RELEASE',
  EVENT: 'EVENT',
  PLAYLIST: 'PLAYLIST',
  ARTIST: 'ARTIST',
  ANNOUNCEMENT: 'ANNOUNCEMENT'
};

const BANNER_POSITION = {
  HOME_TOP: 'HOME_TOP',
  HOME_MIDDLE: 'HOME_MIDDLE',
  SEARCH_TOP: 'SEARCH_TOP',
  LIBRARY_TOP: 'LIBRARY_TOP',
  PROFILE_TOP: 'PROFILE_TOP'
};

const BANNER_ACTION_TYPE = {
  NONE: 'NONE',
  OPEN_URL: 'OPEN_URL',
  OPEN_PLAYLIST: 'OPEN_PLAYLIST',
  OPEN_ALBUM: 'OPEN_ALBUM',
  OPEN_ARTIST: 'OPEN_ARTIST',
  PLAY_SONG: 'PLAY_SONG'
};

// ===== CONFIGURATION =====
const CONFIGURATION_CATEGORY = {
  GENERAL: 'GENERAL',
  PLAYBACK: 'PLAYBACK',
  SOCIAL: 'SOCIAL',
  ROOM: 'ROOM',
  RECOMMENDATION: 'RECOMMENDATION',
  NOTIFICATION: 'NOTIFICATION',
  LIMITS: 'LIMITS',
  FEATURES: 'FEATURES'
};

const CONFIGURATION_DATA_TYPE = {
  STRING: 'STRING',
  NUMBER: 'NUMBER',
  BOOLEAN: 'BOOLEAN',
  JSON: 'JSON',
  ARRAY: 'ARRAY'
};

// ===== AUDIT LOG =====
const AUDIT_ACTION = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  LOCK_USER: 'LOCK_USER',
  UNLOCK_USER: 'UNLOCK_USER',
  APPROVE_SONG: 'APPROVE_SONG',
  REJECT_SONG: 'REJECT_SONG',
  DELETE_COMMENT: 'DELETE_COMMENT',
  RESOLVE_REPORT: 'RESOLVE_REPORT',
  CHANGE_CONFIG: 'CHANGE_CONFIG',
  GRANT_PERMISSION: 'GRANT_PERMISSION',
  REVOKE_PERMISSION: 'REVOKE_PERMISSION',
  OTHER: 'OTHER'
};

const AUDIT_RESOURCE = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  SONG: 'SONG',
  PLAYLIST: 'PLAYLIST',
  ALBUM: 'ALBUM',
  ARTIST: 'ARTIST',
  COMMENT: 'COMMENT',
  REPORT: 'REPORT',
  BANNER: 'BANNER',
  CONFIGURATION: 'CONFIGURATION',
  ROOM: 'ROOM',
  OTHER: 'OTHER'
};

const AUDIT_SEVERITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
};

// ===== SONG FEATURES (AI) =====
const SONG_MOOD = {
  HAPPY: 'HAPPY',
  SAD: 'SAD',
  ENERGETIC: 'ENERGETIC',
  CALM: 'CALM',
  ROMANTIC: 'ROMANTIC',
  ANGRY: 'ANGRY',
  MELANCHOLIC: 'MELANCHOLIC',
  UPLIFTING: 'UPLIFTING',
  DARK: 'DARK',
  PEACEFUL: 'PEACEFUL'
};

const SONG_MOOD_LABELS = {
  HAPPY: 'Vui vẻ',
  SAD: 'Buồn',
  ENERGETIC: 'Năng động',
  CALM: 'Bình yên',
  ROMANTIC: 'Lãng mạn',
  ANGRY: 'Giận dữ',
  MELANCHOLIC: 'U sầu',
  UPLIFTING: 'Phấn chấn',
  DARK: 'Tối tăm',
  PEACEFUL: 'Yên bình'
};

const SONG_ERA = {
  '1960s': '1960s',
  '1970s': '1970s',
  '1980s': '1980s',
  '1990s': '1990s',
  '2000s': '2000s',
  '2010s': '2010s',
  '2020s': '2020s'
};

// ===== RECOMMENDATION FEEDBACK =====
const FEEDBACK_TYPE = {
  PLAYED: 'PLAYED',
  SKIPPED: 'SKIPPED',
  COMPLETED: 'COMPLETED',
  LIKED: 'LIKED',
  DISLIKED: 'DISLIKED',
  ADDED_TO_PLAYLIST: 'ADDED_TO_PLAYLIST',
  IGNORED: 'IGNORED'
};

const FEEDBACK_TYPE_LABELS = {
  PLAYED: 'Đã phát',
  SKIPPED: 'Bỏ qua',
  COMPLETED: 'Nghe hết',
  LIKED: 'Thích',
  DISLIKED: 'Không thích',
  ADDED_TO_PLAYLIST: 'Thêm vào playlist',
  IGNORED: 'Bỏ qua'
};

// ===== SOCIAL =====
const BLOCK_REASON = {
  SPAM: 'SPAM',
  HARASSMENT: 'HARASSMENT',
  INAPPROPRIATE: 'INAPPROPRIATE',
  OTHER: 'OTHER'
};

const BLOCK_REASON_LABELS = {
  SPAM: 'Spam',
  HARASSMENT: 'Quấy rối',
  INAPPROPRIATE: 'Nội dung không phù hợp',
  OTHER: 'Khác'
};

const DEVICE_TYPE = {
  MOBILE: 'MOBILE',
  TABLET: 'TABLET',
  WEB: 'WEB',
  DESKTOP: 'DESKTOP',
  TV: 'TV',
  SMART_SPEAKER: 'SMART_SPEAKER'
};

const REPEAT_MODE = {
  OFF: 'OFF',
  ONE: 'ONE',
  ALL: 'ALL'
};

// ===== EXPORTS =====
module.exports = {
  USER_STATUS,
  ADMIN_ROLE,
  ADMIN_ROLE_LABELS,
  NOTIFICATION_TYPE,
  NOTIFICATION_TYPE_LABELS,
  REPORT_TYPE,
  REPORT_REASON,
  REPORT_STATUS,
  REPORT_REASON_LABELS,
  REPORT_STATUS_LABELS,
  LOG_LEVEL,
  LOG_CATEGORY,
  ACTOR_TYPE,
  SHARE_TYPE,
  PLAY_CONTEXT,
  TIME_OF_DAY,
  DAY_OF_WEEK,
  RECOMMENDATION_ALGORITHM,
  ResponseCode,
  GENDER,
  GENDER_LABELS,
  LANGUAGE,
  THEME,
  ROOM_ACTIVITY_TYPE,
  ROOM_MESSAGE_TYPE,
  ROOM_INVITATION_STATUS,
  BANNER_TYPE,
  BANNER_POSITION,
  BANNER_ACTION_TYPE,
  CONFIGURATION_CATEGORY,
  CONFIGURATION_DATA_TYPE,
  AUDIT_ACTION,
  AUDIT_RESOURCE,
  AUDIT_SEVERITY,
  SONG_MOOD,
  SONG_MOOD_LABELS,
  SONG_ERA,
  FEEDBACK_TYPE,
  FEEDBACK_TYPE_LABELS,
  BLOCK_REASON,
  BLOCK_REASON_LABELS,
  DEVICE_TYPE,
  REPEAT_MODE
};



